/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AblAmbulanceWlList {
    }
}
declare global {
    interface HTMLAblAmbulanceWlListElement extends Components.AblAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLAblAmbulanceWlListElement: {
        prototype: HTMLAblAmbulanceWlListElement;
        new (): HTMLAblAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "abl-ambulance-wl-list": HTMLAblAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface AblAmbulanceWlList {
    }
    interface IntrinsicElements {
        "abl-ambulance-wl-list": AblAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "abl-ambulance-wl-list": LocalJSX.AblAmbulanceWlList & JSXBase.HTMLAttributes<HTMLAblAmbulanceWlListElement>;
        }
    }
}
